Repository edwardkrupicka/under-a-tack, pull requests merged in 2022-01, with the labels that each got.

#12 Feature/home page
  src/App.js
  src/App.scss
  src/Components/Card/Card.js
  src/Components/Card/Card.scss
  src/Components/Grid/Grid.js
  src/Components/Grid/Grid.scss
  src/Components/Header/Header.js
  src/Components/Header/Header.scss
  src/Components/Image/Image.js
  src/Components/Image/Image.scss
  src/data.js
Labels: enhancement

#21 Add formatting style to Image Page
  src/Components/ImagePage/ImagePage.js
  src/Components/ImagePage/ImagePage.scss
Labels: enhancement

#25 Feature/add to cart
  src/App.js
  src/Components/Card/Card.js
  src/Components/Cart/Cart.js
  src/Components/Cart/Cart.scss
  src/Components/Grid/Grid.js
  src/Components/ImagePage/ImagePage.js
Labels: feature

#29 Revert "Feature/add to cart"
  src/App.js
  src/Components/Card/Card.js
  src/Components/Cart/Cart.js
  src/Components/Cart/Cart.scss
  src/Components/Grid/Grid.js
  src/Components/ImagePage/ImagePage.js
Labels: bug

#30 Feature/add 2 cart
  src/Components/Cart/Cart.js
Labels: enhancement

#32 Fix/main
  src/App.js
  src/Components/Card/Card.js
  src/Components/Card/Card.scss
  src/Components/Cart/Cart.js
  src/Components/Cart/Cart.scss
  src/Components/Grid/Grid.js
  src/Components/ImagePage/ImagePage.js
  src/Components/ImagePage/ImagePage.scss
Labels: refactor

#35 Feature/cypress testing
  cypress/integration/2-advanced-examples/imagePage_spec.js
  cypress/integration/2-advanced-examples/mainPage_spec.js
  cypress/integration/integration/Grid_spec.js
  cypress/integration/integration/imagePage_spec.js
  package-lock.json
  package.json
Labels: enhancement

#37 Feature/styling
  src/App.scss
  src/Components/Card/Card.js
  src/Components/Card/Card.scss
  src/Components/FavoritesGrid/FavoritesGrid.js
  src/Components/FavoritesGrid/FavoritesGrid.scss
  src/Components/Grid/Grid.js
  src/Components/Grid/Grid.scss
  src/Components/Header/Header.js
  src/Components/Header/Header.scss
  src/Components/ImagePage/ImagePage.js
  src/Components/ImagePage/ImagePage.scss
  src/svg/heart.svg
  src/svg/heartFill.svg
Labels: enhancement

#38 quick fix
  src/Components/Grid/Grid.js
Labels: bug

#41 Refactor/cypress
  cypress/integration/integration/Grid_spec.js
  cypress/integration/integration/imagePage_spec.js
  src/Components/Header/Header.js
Labels: fix

#43 Feature/cart update
  src/App.js
  src/Components/Cart/Cart.js
  src/Components/ImagePage/ImagePage.js
  src/Components/ImagePage/ImagePage.scss
Labels: enhancement, refactor, fix
